// js/core/elements.js
window.App = window.App || {};

App.renderAllIcons = function() {
    document.querySelectorAll('[data-icon]').forEach(el => {
        const name = el.dataset.icon;
        const size = el.dataset.iconSize || 'md';
        const svgHtml = App.icon(name, size);
        if (svgHtml) {
            // Извлекаем только содержимое SVG (без внешнего span)
            const match = svgHtml.match(/<svg[^>]*>[\s\S]*<\/svg>/);
            if (match) {
                el.innerHTML = match[0];
                if (!el.classList.contains('icon')) {
                    el.classList.add('icon', `icon-${size}`);
                }
            }
        }
    });
};

App.cacheElements = function() {
    App.elements = {
        tasksBody: document.getElementById('tasksBody'),
        tableHeader: document.getElementById('tableHeader'),
        emptyState: document.getElementById('emptyState'),
        searchInput: document.getElementById('searchInput'),
        themeToggle: document.getElementById('themeToggle'),
        newTaskBtn: document.getElementById('newTaskBtn'),
        emptyNewTaskBtn: document.getElementById('emptyNewTaskBtn'),
        pageTitle: document.getElementById('pageTitle'),
        commandBackdrop: document.getElementById('commandBackdrop'),
        commandPalette: document.getElementById('commandPalette'),
        commandInput: document.getElementById('commandInput'),
        commandResults: document.getElementById('commandResults'),
        modalBackdrop: document.getElementById('modalBackdrop'),
        taskModal: document.getElementById('taskModal'),
        modalTitle: document.getElementById('modalTitle'),
        modalClose: document.getElementById('modalClose'),
        modalCancel: document.getElementById('modalCancel'),
        modalSave: document.getElementById('modalSave'),
        bulkModalBackdrop: document.getElementById('bulkModalBackdrop'),
        bulkModal: document.getElementById('bulkModal'),
        bulkModalTitle: document.getElementById('bulkModalTitle'),
        bulkPriorityBtn: document.getElementById('bulkPriorityBtn'),
        bulkModalClose: document.getElementById('bulkModalClose'),
        bulkModalBody: document.getElementById('bulkModalBody'),
        taskForm: document.getElementById('taskForm'),
        taskTitle: document.getElementById('taskTitle'),
        taskDescription: document.getElementById('taskDescription'),
        taskStatus: document.getElementById('taskStatus'),
        taskPriority: document.getElementById('taskPriority'),
        taskAssigneeTrigger: document.getElementById('taskAssigneeTrigger'),
        taskAssigneeTriggerLabel: document.getElementById('taskAssigneeTriggerLabel'),
        confirmDialogBackdrop: document.getElementById('confirmDialogBackdrop'),
        confirmDialog: document.getElementById('confirmDialog'),
        confirmDialogTitle: document.getElementById('confirmDialogTitle'),
        confirmDialogMessage: document.getElementById('confirmDialogMessage'),
        confirmDialogCancel: document.getElementById('confirmDialogCancel'),
        confirmDialogConfirm: document.getElementById('confirmDialogConfirm'),
        loginStepWorkspaceName: document.getElementById('loginStepWorkspaceName'),
        loginWorkspaceName: document.getElementById('loginWorkspaceName'),
        loginBtnCreateWorkspace: document.getElementById('loginBtnCreateWorkspace'),
        loginBtnCancelWorkspace: document.getElementById('loginBtnCancelWorkspace'),
        taskDueDate: document.getElementById('taskDueDate'),
        taskPrivate: document.getElementById('taskPrivate'),
        assignmentsSubtabs: document.getElementById('assignmentsSubtabs'),
        toastContainer: document.getElementById('toastContainer'),
        drawerBackdrop: document.getElementById('drawerBackdrop'),
        sideDrawer: document.getElementById('sideDrawer'),
        drawerTitle: document.getElementById('drawerTitle'),
        drawerBody: document.getElementById('drawerBody'),
        drawerClose: document.getElementById('drawerClose'),
        drawerFooter: document.getElementById('drawerFooter'),
        fileImport: document.getElementById('fileImport'),
        currentUserDisplay: document.getElementById('currentUserDisplay'),
        toolbar: document.getElementById('toolbar'),
        statusFilterBtn: document.getElementById('statusFilterBtn'),
        statusFilterMenu: document.getElementById('statusFilterMenu'),
        statusFilterItems: document.getElementById('statusFilterItems'),
        assigneeFilterBtn: document.getElementById('assigneeFilterBtn'),
        assigneeFilterMenu: document.getElementById('assigneeFilterMenu'),
        assigneeFilterItems: document.getElementById('assigneeFilterItems'),
        priorityFilterBtn: document.getElementById('priorityFilterBtn'),
        priorityFilterMenu: document.getElementById('priorityFilterMenu'),
        priorityFilterItems: document.getElementById('priorityFilterItems'),
        activeFilters: document.getElementById('activeFilters'),
        sortDropdown: document.getElementById('sortDropdown'),
        sortButton: document.getElementById('sortButton'),
        sortButtonLabel: document.getElementById('sortButtonLabel'),
        sortMenu: document.getElementById('sortMenu'),
        tableView: document.getElementById('tableView'),
        kanbanView: document.getElementById('kanbanView'),
        calendarView: document.getElementById('calendarView'),
        bulkActionsToolbar: document.getElementById('bulkActionsToolbar'),
        bulkActionsInfo: document.getElementById('bulkActionsInfo'),
        bulkDeleteBtn: document.getElementById('bulkDeleteBtn'),
        bulkStatusBtn: document.getElementById('bulkStatusBtn'),
        bulkAssigneeBtn: document.getElementById('bulkAssigneeBtn'),
        bulkClearBtn: document.getElementById('bulkClearBtn'),
        shortcutsHelp: document.getElementById('shortcutsHelp'),
        shortcutsBackdrop: document.getElementById('shortcutsBackdrop'),
        shortcutsClose: document.getElementById('shortcutsClose'),
        welcomeBackdrop: document.getElementById('welcomeBackdrop'),
        welcomeModal: document.getElementById('welcomeModal'),
        welcomeClose: document.getElementById('welcomeClose'),
        welcomeSkip: document.getElementById('welcomeSkip'),
        welcomePrev: document.getElementById('welcomePrev'),
        welcomeNext: document.getElementById('welcomeNext'),
        notificationBell: document.getElementById('notificationBell'),
        notificationPanel: document.getElementById('notificationPanel'),
        notificationList: document.getElementById('notificationList'),
        clearNotificationsBtn: document.getElementById('clearNotificationsBtn'),
        calendarTitle: document.getElementById('calendarTitle'),
        calendarContent: document.getElementById('calendarContent'),
        calendarInbox: document.getElementById('calendarInbox'),
        chatView: document.getElementById('chatView'),
        chatMessages: document.getElementById('chatMessages'),
        chatInput: document.getElementById('chatInput'),
        chatSendBtn: document.getElementById('chatSendBtn'),
        chatConnectionStatus: document.getElementById('chatConnectionStatus'),
        chatCurrentUserLabel: document.getElementById('chatCurrentUserLabel'),
        calendarModeSwitcher: document.getElementById('calendarModeSwitcher'),
        calendarPrev: document.getElementById('calendarPrev'),
        calendarNext: document.getElementById('calendarNext'),
        calendarToday: document.getElementById('calendarToday'),
        searchSuggestions: document.getElementById('searchSuggestions'),
        syncStatusDot: document.getElementById('syncStatusDot'),
        loginScreen: document.getElementById('loginScreen'),
        loginStepDatabase: document.getElementById('loginStepDatabase'),
        loginStepUser: document.getElementById('loginStepUser'),
        loginDatabaseStatus: document.getElementById('loginDatabaseStatus'),
        loginDbName: document.getElementById('loginDbName'),
        loginDbPath: document.getElementById('loginDbPath'),
        loginBtnConnectFolder: document.getElementById('loginBtnConnectFolder'),
        loginBtnSkip: document.getElementById('loginBtnSkip'),
        loginReconnectActions: document.getElementById('loginReconnectActions'),
        loginNormalActions: document.getElementById('loginNormalActions'),
        loginBtnReconnect: document.getElementById('loginBtnReconnect'),
        loginUsersGrid: document.getElementById('loginUsersGrid'),
        loginNewUserName: document.getElementById('loginNewUserName'),
        loginNewUserRole: document.getElementById('loginNewUserRole'),
        loginBtnCreateUser: document.getElementById('loginBtnCreateUser'),
        loginBtnBackToDb: document.getElementById('loginBtnBackToDb'),
        appMain: document.getElementById('appMain'),
        logoutBtn: document.getElementById('logoutBtn'),
    };
};
